using Market_List_Generator.src.Domain.Entities;
using Market_List_Generator.src.Domain.Enums;
using Market_List_Generator.src.Domain.Interfaces;

namespace Market_List_Generator.src.Infrastructure.Repositories;

public class ItemRepository : IItemRepository
{
    private static readonly IReadOnlyList<Item> _items = new List<Item>
    {
        // 100-199 Grains (Grãos e Farinhas)
        new(100, "Arroz", CategoryType.Grains),
        new(101, "Arroz integral", CategoryType.Grains),
        new(102, "Feijão preto", CategoryType.Grains),
        new(103, "Feijão carioca", CategoryType.Grains),
        new(104, "Lentilha", CategoryType.Grains),
        new(105, "Grão-de-bico", CategoryType.Grains),
        new(106, "Ervilha seca", CategoryType.Grains),
        new(107, "Milho de pipoca", CategoryType.Grains),
        new(108, "Farinha de trigo", CategoryType.Grains),
        new(109, "Farinha de mandioca", CategoryType.Grains),
        new(110, "Farinha de rosca", CategoryType.Grains),
        new(111, "Fubá", CategoryType.Grains),
        new(112, "Maizena", CategoryType.Grains),
        new(113, "Aveia", CategoryType.Grains),
        new(114, "Granola", CategoryType.Grains),
        new(115, "Quinoa", CategoryType.Grains),
        new(116, "Chia", CategoryType.Grains),
        new(117, "Linhaça", CategoryType.Grains),
        new(118, "Tapioca", CategoryType.Grains),

        // 200-299 Bakery (Padaria e Biscoitos)
        new(200, "Pão francês", CategoryType.Bakery),
        new(201, "Pão de forma", CategoryType.Bakery),
        new(202, "Pão integral", CategoryType.Bakery),
        new(203, "Pão de hambúrguer", CategoryType.Bakery),
        new(204, "Pão de hot dog", CategoryType.Bakery),
        new(205, "Bisnaguinha", CategoryType.Bakery),
        new(206, "Torradas", CategoryType.Bakery),
        new(207, "Biscoito salgado (cream cracker)", CategoryType.Bakery),
        new(208, "Biscoito água e sal", CategoryType.Bakery),
        new(209, "Biscoito doce (maisena)", CategoryType.Bakery),
        new(210, "Biscoito recheado", CategoryType.Bakery),
        new(211, "Wafer", CategoryType.Bakery),
        new(212, "Rosquinha", CategoryType.Bakery),
        new(213, "Bolo pronto", CategoryType.Bakery),
        new(214, "Massa de pastel", CategoryType.Bakery),
        new(215, "Massa de lasanha", CategoryType.Bakery),
        new(216, "Macarrão espaguete", CategoryType.Bakery),
        new(217, "Macarrão parafuso", CategoryType.Bakery),
        new(218, "Macarrão instantâneo", CategoryType.Bakery),

        // 300-399 Dairy and Eggs
        new(300, "Leite integral", CategoryType.DairyAndEggs),
        new(301, "Leite desnatado", CategoryType.DairyAndEggs),
        new(302, "Leite em pó", CategoryType.DairyAndEggs),
        new(303, "Leite condensado", CategoryType.DairyAndEggs),
        new(304, "Creme de leite", CategoryType.DairyAndEggs),
        new(305, "Nata", CategoryType.DairyAndEggs),
        new(306, "Manteiga", CategoryType.DairyAndEggs),
        new(307, "Margarina", CategoryType.DairyAndEggs),
        new(308, "Iogurte natural", CategoryType.DairyAndEggs),
        new(309, "Iogurte com sabor", CategoryType.DairyAndEggs),
        new(310, "Queijo mussarela", CategoryType.DairyAndEggs),
        new(311, "Queijo prato", CategoryType.DairyAndEggs),
        new(312, "Queijo minas", CategoryType.DairyAndEggs),
        new(313, "Queijo parmesão ralado", CategoryType.DairyAndEggs),
        new(314, "Requeijão", CategoryType.DairyAndEggs),
        new(315, "Cream cheese", CategoryType.DairyAndEggs),
        new(316, "Doce de leite", CategoryType.DairyAndEggs),
        new(317, "Ovos", CategoryType.DairyAndEggs),

        // 400-499 Meats (Carnes e Frios)
        new(400, "Peito de frango", CategoryType.Meats),
        new(401, "Coxa e sobrecoxa", CategoryType.Meats),
        new(402, "Asa de frango", CategoryType.Meats),
        new(403, "Frango inteiro", CategoryType.Meats),
        new(404, "Carne moída", CategoryType.Meats),
        new(405, "Alcatra", CategoryType.Meats),
        new(406, "Patinho", CategoryType.Meats),
        new(407, "Contra filé", CategoryType.Meats),
        new(408, "Costela", CategoryType.Meats),
        new(409, "Picanha", CategoryType.Meats),
        new(410, "Carne de porco (lombo)", CategoryType.Meats),
        new(411, "Bisteca suína", CategoryType.Meats),
        new(412, "Linguiça toscana", CategoryType.Meats),
        new(413, "Linguiça calabresa", CategoryType.Meats),
        new(414, "Salsicha", CategoryType.Meats),
        new(415, "Bacon", CategoryType.Meats),
        new(416, "Presunto", CategoryType.Meats),
        new(417, "Peito de peru", CategoryType.Meats),
        new(418, "Mortadela", CategoryType.Meats),
        new(419, "Salame", CategoryType.Meats),
        new(420, "Peixe (filé)", CategoryType.Meats),
        new(421, "Salmão", CategoryType.Meats),
        new(422, "Atum em lata", CategoryType.Meats),
        new(423, "Sardinha em lata", CategoryType.Meats),

        // 500-599 Produce (Hortifruti)
        new(500, "Alface", CategoryType.Produce),
        new(501, "Rúcula", CategoryType.Produce),
        new(502, "Tomate", CategoryType.Produce),
        new(503, "Cebola", CategoryType.Produce),
        new(504, "Alho", CategoryType.Produce),
        new(505, "Batata", CategoryType.Produce),
        new(506, "Batata doce", CategoryType.Produce),
        new(507, "Cenoura", CategoryType.Produce),
        new(508, "Beterraba", CategoryType.Produce),
        new(509, "Chuchu", CategoryType.Produce),
        new(510, "Abobrinha", CategoryType.Produce),
        new(511, "Abóbora", CategoryType.Produce),
        new(512, "Pepino", CategoryType.Produce),
        new(513, "Pimentão", CategoryType.Produce),
        new(514, "Brócolis", CategoryType.Produce),
        new(515, "Couve", CategoryType.Produce),
        new(516, "Repolho", CategoryType.Produce),
        new(517, "Couve-flor", CategoryType.Produce),
        new(518, "Berinjela", CategoryType.Produce),
        new(519, "Mandioca (Aipim)", CategoryType.Produce),
        new(520, "Inhame", CategoryType.Produce),
        new(521, "Milho verde", CategoryType.Produce),
        new(522, "Cheiro verde", CategoryType.Produce),
        new(523, "Gengibre", CategoryType.Produce),
        new(524, "Banana", CategoryType.Produce),
        new(525, "Maçã", CategoryType.Produce),
        new(526, "Laranja", CategoryType.Produce),
        new(527, "Limão", CategoryType.Produce),
        new(528, "Mamão", CategoryType.Produce),
        new(529, "Melancia", CategoryType.Produce),
        new(530, "Melão", CategoryType.Produce),
        new(531, "Abacaxi", CategoryType.Produce),
        new(532, "Uva", CategoryType.Produce),
        new(533, "Morango", CategoryType.Produce),
        new(534, "Manga", CategoryType.Produce),
        new(535, "Pera", CategoryType.Produce),
        new(536, "Goiaba", CategoryType.Produce),
        new(537, "Tangerina", CategoryType.Produce),
        new(538, "Abacate", CategoryType.Produce),
        new(539, "Coco", CategoryType.Produce),

        // 600-699 Condiments and Spices
        new(600, "Sal", CategoryType.CondimentsAndSpices),
        new(601, "Sal grosso", CategoryType.CondimentsAndSpices),
        new(602, "Açúcar refinado", CategoryType.CondimentsAndSpices),
        new(603, "Açúcar mascavo", CategoryType.CondimentsAndSpices),
        new(604, "Adoçante", CategoryType.CondimentsAndSpices),
        new(605, "Óleo de soja", CategoryType.CondimentsAndSpices),
        new(606, "Óleo de girassol", CategoryType.CondimentsAndSpices),
        new(607, "Azeite de oliva", CategoryType.CondimentsAndSpices),
        new(608, "Vinagre", CategoryType.CondimentsAndSpices),
        new(609, "Molho de tomate", CategoryType.CondimentsAndSpices),
        new(610, "Extrato de tomate", CategoryType.CondimentsAndSpices),
        new(611, "Ketchup", CategoryType.CondimentsAndSpices),
        new(612, "Mostarda", CategoryType.CondimentsAndSpices),
        new(613, "Maionese", CategoryType.CondimentsAndSpices),
        new(614, "Molho inglês", CategoryType.CondimentsAndSpices),
        new(615, "Molho shoyu", CategoryType.CondimentsAndSpices),
        new(616, "Molho barbecue", CategoryType.CondimentsAndSpices),
        new(617, "Pimenta em molho", CategoryType.CondimentsAndSpices),
        new(618, "Tempero completo", CategoryType.CondimentsAndSpices),
        new(619, "Colorau", CategoryType.CondimentsAndSpices),
        new(620, "Cominho", CategoryType.CondimentsAndSpices),
        new(621, "Orégano", CategoryType.CondimentsAndSpices),
        new(622, "Pimenta do reino", CategoryType.CondimentsAndSpices),
        new(623, "Alho em pó", CategoryType.CondimentsAndSpices),
        new(624, "Louro (folhas)", CategoryType.CondimentsAndSpices),
        new(625, "Canela", CategoryType.CondimentsAndSpices),
        new(626, "Páprica", CategoryType.CondimentsAndSpices),
        new(627, "Caldo de galinha", CategoryType.CondimentsAndSpices),
        new(628, "Caldo de carne", CategoryType.CondimentsAndSpices),
        new(629, "Caldo de legumes", CategoryType.CondimentsAndSpices),
        new(630, "Fermento em pó", CategoryType.CondimentsAndSpices),
        new(631, "Fermento biológico", CategoryType.CondimentsAndSpices),
        new(632, "Mel", CategoryType.CondimentsAndSpices),

        // 700-799 Beverages
        new(700, "Café em pó", CategoryType.Beverages),
        new(701, "Café em cápsula", CategoryType.Beverages),
        new(702, "Café solúvel", CategoryType.Beverages),
        new(703, "Achocolatado em pó", CategoryType.Beverages),
        new(704, "Chocolate quente", CategoryType.Beverages),
        new(705, "Suco de caixinha", CategoryType.Beverages),
        new(706, "Suco em pó", CategoryType.Beverages),
        new(707, "Suco concentrado", CategoryType.Beverages),
        new(708, "Refrigerante cola", CategoryType.Beverages),
        new(709, "Refrigerante guaraná", CategoryType.Beverages),
        new(710, "Refrigerante limão", CategoryType.Beverages),
        new(711, "Água mineral", CategoryType.Beverages),
        new(712, "Água com gás", CategoryType.Beverages),
        new(713, "Água de coco", CategoryType.Beverages),
        new(714, "Chá em sachê", CategoryType.Beverages),
        new(715, "Chá gelado", CategoryType.Beverages),
        new(716, "Energético", CategoryType.Beverages),
        new(717, "Isotônico", CategoryType.Beverages),

        // 800-899 Snacks (Doces e Lanches)
        new(800, "Chocolate em barra", CategoryType.Snacks),
        new(801, "Bombom", CategoryType.Snacks),
        new(802, "Bala", CategoryType.Snacks),
        new(803, "Chiclete", CategoryType.Snacks),
        new(804, "Gelatina", CategoryType.Snacks),
        new(805, "Pudim pronto", CategoryType.Snacks),
        new(806, "Salgadinho", CategoryType.Snacks),
        new(807, "Batata chips", CategoryType.Snacks),
        new(808, "Amendoim", CategoryType.Snacks),
        new(809, "Castanha de caju", CategoryType.Snacks),
        new(810, "Castanha do Pará", CategoryType.Snacks),
        new(811, "Mix de nuts", CategoryType.Snacks),
        new(812, "Barra de cereal", CategoryType.Snacks),
        new(813, "Paçoca", CategoryType.Snacks),
        new(814, "Pé-de-moleque", CategoryType.Snacks),
        new(815, "Geléia", CategoryType.Snacks),

        // 900-999 Frozen (Congelados)
        new(900, "Sorvete pote", CategoryType.Frozen),
        new(901, "Picolé", CategoryType.Frozen),
        new(902, "Pizza congelada", CategoryType.Frozen),
        new(903, "Lasanha congelada", CategoryType.Frozen),
        new(904, "Batata pré-frita", CategoryType.Frozen),
        new(905, "Nuggets", CategoryType.Frozen),
        new(906, "Hambúrguer congelado", CategoryType.Frozen),
        new(907, "Kibe congelado", CategoryType.Frozen),
        new(908, "Pão de queijo congelado", CategoryType.Frozen),
        new(909, "Legumes congelados", CategoryType.Frozen),
        new(910, "Polpa de fruta", CategoryType.Frozen),
        new(911, "Peixe congelado", CategoryType.Frozen),

        // 1000-1099 Alcoholic
        new(1000, "Cerveja lata", CategoryType.Alcoholic),
        new(1001, "Cerveja long neck", CategoryType.Alcoholic),
        new(1002, "Cerveja garrafa", CategoryType.Alcoholic),
        new(1003, "Vinho tinto", CategoryType.Alcoholic),
        new(1004, "Vinho branco", CategoryType.Alcoholic),
        new(1005, "Espumante", CategoryType.Alcoholic),
        new(1006, "Cachaça", CategoryType.Alcoholic),
        new(1007, "Vodka", CategoryType.Alcoholic),
        new(1008, "Whisky", CategoryType.Alcoholic),
        new(1009, "Gin", CategoryType.Alcoholic),
        new(1010, "Rum", CategoryType.Alcoholic),
        new(1011, "Licor", CategoryType.Alcoholic),

        // 1100-1199 Cleaning
        new(1100, "Sabão em pó", CategoryType.Cleaning),
        new(1101, "Sabão líquido", CategoryType.Cleaning),
        new(1102, "Sabão em barra", CategoryType.Cleaning),
        new(1103, "Amaciante", CategoryType.Cleaning),
        new(1104, "Alvejante", CategoryType.Cleaning),
        new(1105, "Detergente", CategoryType.Cleaning),
        new(1106, "Esponja de louça", CategoryType.Cleaning),
        new(1107, "Palha de aço", CategoryType.Cleaning),
        new(1108, "Água sanitária", CategoryType.Cleaning),
        new(1109, "Desinfetante", CategoryType.Cleaning),
        new(1110, "Limpador multiuso", CategoryType.Cleaning),
        new(1111, "Desengordurante", CategoryType.Cleaning),
        new(1112, "Limpa vidros", CategoryType.Cleaning),
        new(1113, "Limpador de piso", CategoryType.Cleaning),
        new(1114, "Lustra móveis", CategoryType.Cleaning),
        new(1115, "Limpador de banheiro", CategoryType.Cleaning),
        new(1116, "Saco de lixo", CategoryType.Cleaning),
        new(1117, "Pano de chão", CategoryType.Cleaning),
        new(1118, "Pano multiuso", CategoryType.Cleaning),
        new(1119, "Vassoura", CategoryType.Cleaning),
        new(1120, "Rodo", CategoryType.Cleaning),
        new(1121, "Luva de limpeza", CategoryType.Cleaning),

        // 1200-1299 Personal Hygiene
        new(1200, "Sabonete em barra", CategoryType.PersonalHygiene),
        new(1201, "Sabonete líquido", CategoryType.PersonalHygiene),
        new(1202, "Shampoo", CategoryType.PersonalHygiene),
        new(1203, "Condicionador", CategoryType.PersonalHygiene),
        new(1204, "Creme de pentear", CategoryType.PersonalHygiene),
        new(1205, "Desodorante", CategoryType.PersonalHygiene),
        new(1206, "Pasta de dente", CategoryType.PersonalHygiene),
        new(1207, "Escova de dente", CategoryType.PersonalHygiene),
        new(1208, "Fio dental", CategoryType.PersonalHygiene),
        new(1209, "Enxaguante bucal", CategoryType.PersonalHygiene),
        new(1210, "Papel higiênico", CategoryType.PersonalHygiene),
        new(1211, "Absorvente", CategoryType.PersonalHygiene),
        new(1212, "Fralda descartável", CategoryType.PersonalHygiene),
        new(1213, "Lenço umedecido", CategoryType.PersonalHygiene),
        new(1214, "Creme hidratante", CategoryType.PersonalHygiene),
        new(1215, "Protetor solar", CategoryType.PersonalHygiene),
        new(1216, "Repelente", CategoryType.PersonalHygiene),
        new(1217, "Aparelho de barbear", CategoryType.PersonalHygiene),
        new(1218, "Creme de barbear", CategoryType.PersonalHygiene),
        new(1219, "Cotonete", CategoryType.PersonalHygiene),
        new(1220, "Algodão", CategoryType.PersonalHygiene),
        new(1221, "Perfume", CategoryType.PersonalHygiene),

        // 1300-1399 Pets
        new(1300, "Ração para cachorro", CategoryType.Pets),
        new(1301, "Ração para gato", CategoryType.Pets),
        new(1302, "Ração úmida (sachê)", CategoryType.Pets),
        new(1303, "Petisco pet", CategoryType.Pets),
        new(1304, "Osso para cachorro", CategoryType.Pets),
        new(1305, "Areia para gato", CategoryType.Pets),
        new(1306, "Tapete higiênico", CategoryType.Pets),
        new(1307, "Shampoo pet", CategoryType.Pets),
        new(1308, "Antipulgas", CategoryType.Pets),
        new(1309, "Brinquedo pet", CategoryType.Pets),

        // 1400-1499 Utilities (Utilidades e Bazar)
        new(1400, "Papel filme", CategoryType.Utilities),
        new(1401, "Papel manteiga", CategoryType.Utilities),
        new(1402, "Papel alumínio", CategoryType.Utilities),
        new(1403, "Papel toalha", CategoryType.Utilities),
        new(1404, "Guardanapo", CategoryType.Utilities),
        new(1405, "Filtro de café", CategoryType.Utilities),
        new(1406, "Palito de dente", CategoryType.Utilities),
        new(1407, "Pilha AA", CategoryType.Utilities),
        new(1408, "Pilha AAA", CategoryType.Utilities),
        new(1409, "Lâmpada", CategoryType.Utilities),
        new(1410, "Fósforo", CategoryType.Utilities),
        new(1411, "Isqueiro", CategoryType.Utilities),
        new(1412, "Vela", CategoryType.Utilities),
        new(1413, "Copo descartável", CategoryType.Utilities),
        new(1414, "Prato descartável", CategoryType.Utilities),
        new(1415, "Talher descartável", CategoryType.Utilities),
        new(1416, "Canudo", CategoryType.Utilities),
        new(1417, "Sacola plástica", CategoryType.Utilities),
        new(1418, "Marmita descartável", CategoryType.Utilities),
    };

    public IReadOnlyList<Item> GetAll() => _items;
}
